name       : flashrom
version    : 1.2
release    : 4
source     :
    - https://download.flashrom.org/releases/flashrom-v1.2.tar.bz2 : e1f8d95881f5a4365dfe58776ce821dfcee0f138f75d0f44f8a3cd032d9ea42b
license    : GPL-2.0-or-later
component  : system.utils
summary    : flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips.
description: |
    flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips. It is designed to flash BIOS/EFI/coreboot/firmware/optionROM images on mainboards, network/graphics/storage controller cards, and various other programmer devices.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(libusb)
    - pkgconfig(libftdi1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
