name       : flashrom
version    : 1.1
release    : 3
source     :
    - https://download.flashrom.org/releases/flashrom-v1.1.tar.bz2 : aeada9c70c22421217c669356180c0deddd0b60876e63d2224e3260b90c14e19
license    : GPL-2.0-or-later
component  : system.utils
summary    : flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips.
description: |
    flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips. It is designed to flash BIOS/EFI/coreboot/firmware/optionROM images on mainboards, network/graphics/storage controller cards, and various other programmer devices.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(libusb)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
