name       : flashrom
version    : 1.0.1
release    : 2
source     :
    - https://download.flashrom.org/releases/flashrom-v1.0.1.tar.bz2 : d579f8dda5b69eeab55a658d59ffbe185443e4e8477e751aaf38c36468cede44
license    : GPL-2.0-or-later
component  : system.utils
summary    : flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips.
description: |
    flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips. It is designed to flash BIOS/EFI/coreboot/firmware/optionROM images on mainboards, network/graphics/storage controller cards, and various other programmer devices.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(libusb)
setup      : |
    %patch -p1 < $pkgfiles/0001-avoid-deprecated-libusb-functions.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
