name       : flashrom
version    : 1.0
release    : 1
source     :
    - https://download.flashrom.org/releases/flashrom-1.0.tar.bz2 : 3702fa215ba5fb5af8e54c852d239899cfa1389194c1e51cb2a170c4dc9dee64
license    : GPL-2.0-or-later
component  : system.utils
summary    : flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips.
description: |
    flashrom is a utility for identifying, reading, writing, verifying and erasing flash chips. It is designed to flash BIOS/EFI/coreboot/firmware/optionROM images on mainboards, network/graphics/storage controller cards, and various other programmer devices.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(libusb)
setup      : |
    %patch -p1 < $pkgfiles/0001-avoid-deprecated-libusb-functions.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
